### ISSUE TITLE
Refactor, use simplified Logrus logger. 

### ISSUE THREAD

**Issue by gavinelder** [mdmdirector/mdmdirector#13]
We should create a single logger with context using logrus, this was we can track requests , remove log.go and simplify the overall logic & unneeded boiler plate.

# From the docs
## Level logging
Logrus has seven logging levels: Trace, Debug, Info, Warning, Error, Fatal and Panic.

```
log.Trace("Something very low level.")
log.Debug("Useful debugging information.")
log.Info("Something noteworthy happened!")
log.Warn("You should probably take a look at this.")
log.Error("Something failed but I'm not quitting.")
// Calls os.Exit(1) after logging
log.Fatal("Bye.")
// Calls panic() after logging
log.Panic("I'm bailing.")
```

You can set the logging level on a Logger, then it will only log entries with that severity or anything above it:

// Will log anything that is info or above (warn, error, fatal, panic). Default.
```
log.SetLevel(log.InfoLevel)
```
It may be useful to set log.Level = logrus.DebugLevel in a debug or verbose environment if your application has that.

**Comment by grahamgilbert** [comment]
Okay that’s fine. I was planning on adding more fields, such as udid, uuid etc. If we can do this without the wrapper, then fine but the wrapper seemed like the best way to do it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
